# FICTIONAL demo config for hackathon. Not from any real organization.
# Palo Alto-style (set commands). NON-COMPLIANT version: intentionally insecure.
set deviceconfig system hostname PaloAlto-FW-02
delete deviceconfig system ntp-servers
delete deviceconfig system log-settings
set deviceconfig system telnet enabled yes
delete deviceconfig system ssh
set deviceconfig system web-server http-enabled yes
set deviceconfig system web-server https-enabled no
set deviceconfig system snmp-setting community public
set deviceconfig system snmp-setting community private
set shared admin admin password admin123
set shared admin guest password guest
set deviceconfig system password-complexity enabled no
set rulebase security rules Allow-All action allow source any destination any
set network telnet enabled yes
