"""Demo compliance rules NET-001..NET-010 (stored separately from engine logic).

Honest labeling: framework is ["Demo Security Rule"] unless an official
control has been verified. Add more rules later by appending to this list
and re-running seed_rules.py. No compliance code changes needed.
"""

DEMO_RULES: list[dict] = [
    {
        "rule_code": "NET-001",
        "title": "Telnet must be disabled",
        "category": "Secure Management",
        "severity": "HIGH",
        "framework": ["Demo Security Rule"],
        "field": "management.telnet_enabled",
        "expected": False,
        "description": "Telnet transmits credentials without adequate protection.",
        "remediation": "Disable Telnet and use SSH for secure management.",
    },
    {
        "rule_code": "NET-002",
        "title": "SSH should be enabled for secure remote administration",
        "category": "Secure Management",
        "severity": "HIGH",
        "framework": ["Demo Security Rule"],
        "field": "management.ssh_enabled",
        "expected": True,
        "description": "SSH encrypts management traffic; without it admins fall back to insecure methods.",
        "remediation": "Enable SSH version 2 and restrict VTY/management access to SSH only.",
    },
    {
        "rule_code": "NET-003",
        "title": "HTTP management should be disabled where HTTPS is available",
        "category": "Secure Management",
        "severity": "MEDIUM",
        "framework": ["Demo Security Rule"],
        "field": "management.http_enabled",
        "expected": False,
        "description": "Plain HTTP management exposes credentials and session data.",
        "remediation": "Disable HTTP management and use HTTPS only.",
    },
    {
        "rule_code": "NET-004",
        "title": "Logging should be enabled",
        "category": "Logging",
        "severity": "MEDIUM",
        "framework": ["Demo Security Rule"],
        "field": "logging.enabled",
        "expected": True,
        "description": "Without logging there is no record of security-relevant events.",
        "remediation": "Configure buffered logging and a remote syslog host.",
    },
    {
        "rule_code": "NET-005",
        "title": "Insecure SNMP community strings must not be used",
        "category": "SNMP",
        "severity": "HIGH",
        "framework": ["Demo Security Rule"],
        "field": "snmp.insecure",
        "expected": False,
        "pass_on_none": True,  # No SNMP info at all still means "no insecure community seen".
        "description": "SNMPv1/v2 community strings like public/private are easily guessed.",
        "remediation": "Remove public/private communities; use SNMPv3 with auth/priv only.",
    },
    {
        "rule_code": "NET-006",
        "title": "NTP should be configured for reliable time synchronization",
        "category": "System",
        "severity": "LOW",
        "framework": ["Demo Security Rule"],
        "field": "ntp.configured",
        "expected": True,
        "description": "Wrong device time breaks log correlation and certificate checks.",
        "remediation": "Configure at least one trusted NTP server.",
    },
    {
        "rule_code": "NET-007",
        "title": "Administrative access should be restricted",
        "category": "Access Control",
        "severity": "HIGH",
        "framework": ["Demo Security Rule"],
        "field": "management.mgmt_restricted",
        "expected": True,
        "description": "Unrestricted management access lets any host attempt admin login.",
        "remediation": "Restrict management with ACLs / access-class / firewall zones.",
    },
    {
        "rule_code": "NET-008",
        "title": "Weak/default administrative credentials must not be used",
        "category": "Authentication",
        "severity": "CRITICAL",
        "framework": ["Demo Security Rule"],
        "field": "authentication.weak_creds_found",
        "expected": False,
        "pass_on_none": True,  # No credential lines seen -> nothing weak detected.
        "description": "Default passwords like admin/admin123 are the first attackers try.",
        "remediation": "Replace weak passwords with strong secrets and hashed credentials.",
    },
    {
        "rule_code": "NET-009",
        "title": "Unnecessary management services should be disabled",
        "category": "Secure Management",
        "severity": "MEDIUM",
        "framework": ["Demo Security Rule"],
        "field": "management.unnecessary_services",
        "expected": False,
        "pass_on_none": True,  # No extra services mentioned -> nothing bad found.
        "description": "Extra services (finger, pad, telnet, plain HTTP) widen the attack surface.",
        "remediation": "Disable finger/pad/source-route/telnet/HTTP; keep only needed services.",
    },
    {
        "rule_code": "NET-010",
        "title": "Security logging should be configured",
        "category": "Logging",
        "severity": "MEDIUM",
        "framework": ["Demo Security Rule"],
        "field": "logging.security_logging",
        "expected": True,
        "description": "Security events must be recorded for detection and forensics.",
        "remediation": "Enable security/audit logging to buffer and syslog with info level or higher.",
    },
]
