! FICTIONAL demo config for hackathon. Not from any real organization.
! Cisco-style. COMPLIANT version: secure management, logging, NTP, SNMPv3 only.
hostname Cisco-Router-01
!
no service telnet
service password-encryption
no service finger
no service pad
no ip source-route
!
ip ssh version 2
ip ssh time-out 60
ip ssh authentication-retries 2
!
line vty 0 4
 transport input ssh
 exec-timeout 10 0
 access-class 10 in
!
access-list 10 permit 10.0.0.0 0.0.0.255
access-list 10 deny any log
!
no ip http server
ip http secure-server
ip http authentication local
!
logging buffered 16384 informational
logging host 10.0.0.50
logging trap informational
!
ntp server 10.0.0.10
ntp server 10.0.0.11
ntp authenticate
!
no snmp-server community public
no snmp-server community private
snmp-server group AUDIT-GROUP v3 priv
snmp-server user audit-user AUDIT-GROUP v3 auth sha S3cure-Demo-Hash priv aes 128 S3cure-Demo-Priv
!
username netadmin privilege 15 secret S3cure-P@ssw0rd-2026!
enable secret S3cure-En@ble-2026!
!
end
